// ADDRESSSES
const addresses = [
  {
    id: 0,
    city: "Jerusalem",
    address: "King george 22",
    deliveryType: "medicine",
    frequency: "High",
    recipientName: "John",
    recipientPhone: "972 54-333-4444",
  },
  {
    id: 1,
    city: "Haifa",
    address: "Bar gyora 10",
    deliveryType: "medicine",
    frequency: "High",
    recipientName: "James",
    recipientPhone: "+972-54-333-4444",
  },
  {
    id: 2,
    city: "Tel-Aviv",
    address: "Shenkin 20",
    deliveryType: "medicine",
    frequency: "Low",
    recipientName: "Sarah",
    recipientPhone: "02-3334444",
  },
  {
    id: 3,
    city: "Eilat",
    address: "Hanachal 12",
    deliveryType: "medicine",
    frequency: "Low",
    recipientName: "Josh",
    recipientPhone: "02 3334444",
  },
  {
    id: 4,
    city: "Ra'anana",
    address: "Haneviim 3",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Julian",
    recipientPhone: "023334444",
  },
  {
    id: 5,
    city: "Zichron",
    address: "Neve 15",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Natasha",
    recipientPhone: "050-333-4444",
  },
  {
    id: 6,
    city: "Tiberia",
    address: "Kineret 6",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Ron",
    recipientPhone: "(+972)54-333-4444",
  },
];
// DRIVERS
const drivers = [
  {
    id: 0,
    firstName: "Jason",
    lastName: "Jones",
    phone: "+(972)50 333 4444",
    distributionArea: "North",
  },
  {
    id: 1,
    firstName: "Johanna",
    lastName: "Smith",
    phone: "0753334444",
    distributionArea: "South",
  },
  {
    id: 2,
    firstName: "Ray",
    lastName: "Johnson",
    phone: "+(972)50 355 4234",
    distributionArea: "East",
  },
  {
    id: 3,
    firstName: "John",
    lastName: "Williams",
    phone: "050-721-2001",
    distributionArea: "South",
  },
  {
    id: 4,
    firstName: "Lana",
    lastName: "Brown",
    phone: "+(972)50 721 2001",
    distributionArea: "North",
  },
  {
    id: 5,
    firstName: "Emma",
    lastName: "Davis",
    phone: "+972-54-213-4488",
    distributionArea: "South",
  },
  {
    id: 6,
    firstName: "Harry",
    lastName: "Miller",
    phone: "02 6510655",
    distributionArea: "West",
  },
];

const deliveryAddresses = [
  {
    id: 0,
    city: "Jerusalem",
    address: "King george 22",
    deliveryType: "medicine",
    frequency: "High",
    recipientName: "John",
    recipientPhone: "972 54-333-4444",
    done: null,
  },
  {
    id: 1,
    city: "Haifa",
    address: "Bar gyora 10",
    deliveryType: "medicine",
    frequency: "High",
    recipientName: "James",
    recipientPhone: "+972-54-333-4444",
    done: null,
  },
  {
    id: 2,
    city: "Tel-Aviv",
    address: "Shenkin 20",
    deliveryType: "medicine",
    frequency: "Low",
    recipientName: "Sarah",
    recipientPhone: "02-3334444",
    done: null,
  },
  {
    id: 3,
    city: "Eilat",
    address: "Hanachal 12",
    deliveryType: "medicine",
    frequency: "Low",
    recipientName: "Josh",
    recipientPhone: "02 3334444",
    done: null,
  },
  {
    id: 4,
    city: "Ra'anana",
    address: "Haneviim 3",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Julian",
    recipientPhone: "023334444",
    done: null,
  },
  {
    id: 5,
    city: "Zichron",
    address: "Neve 15",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Natasha",
    recipientPhone: "050-333-4444",
    done: null,
  },
  {
    id: 6,
    city: "Tiberia",
    address: "Kineret 6",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Ron",
    recipientPhone: "(+972)54-333-4444",
    done: null,
  },
];

module.exports = { drivers, addresses, deliveryAddresses };
// module.exports = {drivers: drivers, addresses: addresses};
