// ADDRESSSES
const addresses = [
  {
    id: 0,
    city: "Jerusalem",
    address: "King george 22",
    deliveryType: "medicine",
    frequency: "High",
    recipientName: "John",
    recipientPhone: "0528736440",
  },
  {
    id: 1,
    city: "Haifa",
    address: "Bar gyora 10",
    deliveryType: "medicine",
    frequency: "High",
    recipientName: "James",
    recipientPhone: "0503827110",
  },
  {
    id: 2,
    city: "Tel-Aviv",
    address: "Shenkin 20",
    deliveryType: "medicine",
    frequency: "Low",
    recipientName: "Sarah",
    recipientPhone: "0507231009",
  },
  {
    id: 3,
    city: "Eilat",
    address: "Hanachal 12",
    deliveryType: "medicine",
    frequency: "Low",
    recipientName: "Josh",
    recipientPhone: "026745899",
  },
  {
    id: 4,
    city: "Ra'anana",
    address: "Haneviim 3",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Julian",
    recipientPhone: "0507837664",
  },
  {
    id: 5,
    city: "Zichron",
    address: "Neve 15",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Natasha",
    recipientPhone: "0523478660",
  },
  {
    id: 6,
    city: "Tiberia",
    address: "Kineret 6",
    deliveryType: "food",
    frequency: "Low",
    recipientName: "Ron",
    recipientPhone: "0504323119",
  },
];
// DRIVERS
const drivers = [
  {
    id: 0,
    firstName: "Jason",
    lastName: "Jones",
    phone: "0523473667",
    distributionArea: "North",
  },
  {
    id: 1,
    firstName: "Johanna",
    lastName: "Smith",
    phone: "0502876485",
    distributionArea: "South",
  },
  {
    id: 2,
    firstName: "Ray",
    lastName: "Johnson",
    phone: "0502874995",
    distributionArea: "East",
  },
  {
    id: 3,
    firstName: "John",
    lastName: "Williams",
    phone: "0507284775",
    distributionArea: "South",
  },
  {
    id: 4,
    firstName: "Lana",
    lastName: "Brown",
    phone: "0502875996",
    distributionArea: "North",
  },
  {
    id: 5,
    firstName: "Emma",
    lastName: "Davis",
    phone: "0538759665",
    distributionArea: "South",
  },
  {
    id: 6,
    firstName: "Harry",
    lastName: "Miller",
    phone: "0528475996",
    distributionArea: "West",
  },
];

module.exports = { drivers, addresses };
// module.exports = {drivers: drivers, addresses: addresses};
